######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 10 12:33:46 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Application.h Atom.h GraphicWidget.h Residue.h
SOURCES += Application.cpp Atom.cpp GraphicWidget.cpp main.cpp Residue.cpp
